import React from 'react';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { LEGAL_DISCLAIMER } from '@/config/constants';
import {
  Scale,
  ShieldCheck,
  FileText,
  AlertTriangle,
  CreditCard,
  UserCheck,
  Building2,
  Mail,
} from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50 text-slate-900">
      <Navbar />

      {/* Header */}
      <div className="bg-slate-950 text-white py-14 border-b border-slate-800">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-1 rounded-full bg-slate-900 text-emerald-400 border border-slate-800 mb-3">
            <Scale className="w-4 h-4" />
            <span>Legal Documentation</span>
          </div>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight">
            Terms of Service
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-2">
            Last Updated: August 2026 • Effective Immediately
          </p>
        </div>
      </div>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full flex-1 space-y-8 text-xs sm:text-sm text-slate-700 leading-relaxed">
        {/* Core Summary Callout */}
        <div className="p-5 rounded-2xl bg-amber-50 border border-amber-200/80 text-amber-950 space-y-2 shadow-xs">
          <div className="flex items-center gap-2 font-bold text-amber-900 text-sm">
            <AlertTriangle className="w-4 h-4 text-amber-700 shrink-0" />
            <span>Key Summary & Legal Notice</span>
          </div>
          <p className="leading-relaxed text-xs sm:text-sm text-amber-900/90">
            {LEGAL_DISCLAIMER}
          </p>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-10 shadow-xs space-y-8">
          {/* Section 1 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">1.</span>
              <span>Acceptance of Terms & Electronic Record</span>
            </h2>
            <p>
              This document is an electronic record in terms of the <strong>Information Technology Act, 2000</strong> and the rules framed thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p>
              By accessing, browsing, or using the <strong>BhoomiMitra</strong> website, applications, or associated services (collectively, the &quot;Platform&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree with any part of these Terms, you must immediately discontinue use of the Platform.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">2.</span>
              <span>Platform Role: Digital Classifieds Intermediary</span>
            </h2>
            <p>
              BhoomiMitra operates solely as a <strong>digital classifieds and technology intermediary</strong> under Section 79 of the Information Technology Act, 2000. The Platform provides an advertising space and communication medium for property owners (&quot;Sellers&quot;) to showcase land parcels and for prospective purchasers (&quot;Buyers&quot;) to discover and directly contact such owners.
            </p>
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2 text-xs">
              <strong className="text-slate-900 block">Clarification of Platform Scope:</strong>
              <ul className="list-disc pl-5 space-y-1 text-slate-600">
                <li>BhoomiMitra is <strong>not a licensed real estate broker, agent, or property dealer</strong>.</li>
                <li>BhoomiMitra does <strong>not charge any brokerage commission, success fees, or percentage</strong> of any transaction.</li>
                <li>BhoomiMitra is not a party to any contract of sale, agreement of sale, or conveyance executed between Buyers and Sellers.</li>
                <li>BhoomiMitra does not guarantee legal title, encumbrance-free status, or boundary measurements of listed land parcels.</li>
              </ul>
            </div>
          </section>

          {/* Section 3 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">3.</span>
              <span>Seller Warranties, Ownership & Title Documents</span>
            </h2>
            <p>
              Any user creating a listing on BhoomiMitra warrants and covenants that:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-slate-600">
              <li>They are the sole lawful owner of the advertised property or hold a valid, registered, and unrevoked Power of Attorney (PoA) authorizing them to market the property.</li>
              <li>All information, land area measurements, government survey numbers, state portal IDs, and uploaded document scans are truthful, accurate, and up-to-date.</li>
              <li>The land parcel is free from unrevealed litigations, court attachments, government ceiling proceedings, Inam/Wakf/Bhoodan restrictions, or unlawful physical encroachments.</li>
              <li>They agree to keep their listing details accurate and promptly mark properties as &quot;SOLD&quot; or &quot;PAUSED&quot; when no longer available.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">4.</span>
              <span>Classifieds Publishing Fee & Refund Policy</span>
            </h2>
            <p>
              BhoomiMitra charges a nominal flat publishing fee (e.g. ₹10 to ₹25 as configured by platform administrators) to process property submissions, securely store high-resolution title documents in encrypted cloud storage, perform administrative checks, and host the advertisement for a 30-day active visibility period.
            </p>
            <p>
              <strong>No-Refund Policy:</strong> Once a property submission is paid for and administrative document review has commenced, publishing fees are <strong>strictly non-refundable</strong>, irrespective of whether the listing receives the &quot;Verified Property&quot; badge, is rejected due to invalid documentation, or is voluntarily removed by the seller.
            </p>
          </section>

          {/* Section 5 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">5.</span>
              <span>Buyer Due Diligence & Mandatory Inspections</span>
            </h2>
            <p>
              Buyers acknowledge that purchasing real estate in India involves significant legal, financial, and regulatory checks. The &quot;Verified Property&quot; badge indicates only that basic preliminary documentation (such as matching survey IDs and deed scans) was submitted and verified by platform administrators against known records.
            </p>
            <p className="font-semibold text-slate-900">
              Buyers must independently perform the following before paying any token advance or executing agreements:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-600">
              <li>Engage an independent property advocate to conduct a minimum 30-year title search and encumbrance verification.</li>
              <li>Inspect physical land boundaries on-site with a licensed government land surveyor.</li>
              <li>Verify revenue records, Pahani/7-12 extracts, and master plan zoning with the respective Sub-Registrar Office (SRO) and municipal authority.</li>
            </ul>
          </section>

          {/* Section 6 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">6.</span>
              <span>Prohibited Activities & Platform Abuse</span>
            </h2>
            <p>Users agree not to engage in any of the following activities on BhoomiMitra:</p>
            <ul className="list-disc pl-5 space-y-1 text-slate-600">
              <li>Submitting fraudulent, duplicate, or non-existent property listings.</li>
              <li>Automated scraping, crawling, or harvesting of property data, images, or seller phone numbers.</li>
              <li>Circumventing platform authentication, manipulating OTP tokens, or exploiting API endpoints.</li>
              <li>Using buyer inquiry messaging for telemarketing, unsolicited commercial offers, or harassment.</li>
            </ul>
          </section>

          {/* Section 7 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">7.</span>
              <span>Limitation of Liability</span>
            </h2>
            <p>
              To the maximum extent permitted by applicable Indian law, BhoomiMitra, its founders, directors, employees, and technology partners shall not be liable for any direct, indirect, incidental, punitive, or consequential damages arising out of:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-600">
              <li>Any transaction, financial deal, or dispute entered into between Buyers and Sellers.</li>
              <li>Any defect in title, boundary disputes, or fraudulent representations made by listing authors.</li>
              <li>Temporary platform downtime, payment gateway outages, or network interruptions.</li>
            </ul>
          </section>

          {/* Section 8 */}
          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-emerald-700 font-mono">8.</span>
              <span>Governing Law & Jurisdiction</span>
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the Republic of India. Any legal action, suit, or proceeding arising out of or related to these Terms or the Platform shall be subject to the exclusive jurisdiction of the competent courts located in <strong>Hyderabad, Telangana, India</strong>.
            </p>
          </section>
        </div>

        {/* Contact Support Section */}
        <div className="p-6 rounded-2xl bg-slate-900 text-white flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            <h3 className="font-bold text-sm sm:text-base">Have legal questions or grievance queries?</h3>
            <p className="text-xs text-slate-400 mt-0.5">Reach out to our legal and compliance desk directly.</p>
          </div>
          <Link
            href="/contact"
            className="px-5 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-xs font-bold transition-colors shrink-0"
          >
            Contact Legal Desk
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
