import React from 'react';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { LEGAL_DISCLAIMER } from '@/config/constants';
import {
  Scale,
  ShieldCheck,
  FileText,
  AlertTriangle,
  CreditCard,
  Building2,
  Mail,
} from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50 text-slate-900">
      <Navbar />

      {/* Header */}
      <div className="bg-slate-950 text-white py-14 border-b border-slate-800">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-1 rounded-full bg-[#fff1dc] text-[#c75e0a] border border-[#FF9933]/30 mb-3">
            <Scale className="w-4 h-4 text-[#FF9933]" />
            <span>Legal Documentation</span>
          </div>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight">
            Terms of Service
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-2">
            Last Updated: August 2026 • Effective Immediately
          </p>
        </div>
      </div>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full flex-1 space-y-8 text-xs sm:text-sm text-slate-700 leading-relaxed">
        {/* Core Summary Callout */}
        <div className="p-5 rounded-2xl bg-[#fff9f0] border border-[#FF9933]/30 text-[#7a3705] space-y-2 shadow-xs">
          <div className="flex items-center gap-2 font-bold text-slate-950 text-sm">
            <AlertTriangle className="w-4 h-4 text-[#FF9933] shrink-0" />
            <span>Buyer Due Diligence Advisory &amp; Legal Notice</span>
          </div>
          <p className="leading-relaxed text-xs sm:text-sm text-[#9c4c0b]">
            {LEGAL_DISCLAIMER}
          </p>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-10 shadow-xs space-y-8">
          {/* Section 1 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">1.</span>
              <span>Acceptance of Terms &amp; Electronic Record</span>
            </h2>
            <p>
              This document is an electronic record in terms of the <strong>Information Technology Act, 2000</strong> and the rules framed thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p>
              By accessing, browsing, or using the <strong>BhoomiMitra</strong> website, applications, or associated services (collectively, the &quot;Platform&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree with any part of these Terms, you must immediately discontinue use of the Platform.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">2.</span>
              <span>Platform Role: Online Classifieds Marketplace</span>
            </h2>
            <p>
              BhoomiMitra operates as an online classifieds and marketplace platform. The Platform provides listing and advertising infrastructure, property discovery, and direct communication functionality for property owners or authorized representatives (&quot;Sellers&quot;) to showcase land parcels and for prospective purchasers (&quot;Buyers&quot;) to discover and directly contact such sellers. Users are responsible for complying with applicable laws and conducting their own independent due diligence.
            </p>
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-2 text-xs">
              <strong className="text-slate-900 block">Clarification of Platform Scope:</strong>
              <ul className="list-disc pl-5 space-y-1 text-slate-600">
                <li>BhoomiMitra is <strong>not a licensed real estate broker, agent, or property dealer</strong>.</li>
                <li>BhoomiMitra does <strong>not charge any brokerage commission, success fees, or percentage</strong> on transaction completion.</li>
                <li>BhoomiMitra is not a party to any contract of sale, agreement of sale, or conveyance executed between Buyers and Sellers.</li>
                <li>BhoomiMitra does not guarantee legal title, ownership validity, encumbrance-free status, or boundary measurements of listed land parcels.</li>
              </ul>
            </div>
          </section>

          {/* Section 3 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">3.</span>
              <span>Seller Warranties, Representations &amp; Content Standards</span>
            </h2>
            <p>
              Any user creating a listing on BhoomiMitra represents and agrees that:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-slate-600">
              <li>They are the owner of the advertised property or hold valid, lawful authority or Power of Attorney (PoA) to market the property.</li>
              <li>All information, land area measurements, government survey numbers, state portal identifiers, and optional uploaded document scans are accurate and truthful to the best of their knowledge.</li>
              <li>They must not upload unlawful, fraudulent, misleading, or infringing content, or prohibited/disputed land parcels.</li>
              <li>They agree to keep listing details updated and mark properties as &quot;PAUSED&quot; or delete the listing when no longer available.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">4.</span>
              <span>Classifieds Publishing Fee &amp; Direct Listing Policy</span>
            </h2>
            <p>
              BhoomiMitra charges a nominal flat digital publishing fee (e.g. ₹10 to ₹25 as configured on the platform) to host and display seller land advertisements for a 30-day active visibility period. Once payment is completed, the listing is directly published onto the marketplace without administrative delays.
            </p>
            <p>
              <strong>No-Refund Policy:</strong> Once an advertisement submission is paid for and published live, publishing fees are <strong>strictly non-refundable</strong>, as the digital hosting and broadcasting service commences immediately upon payment.
            </p>
          </section>

          {/* Section 5 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">5.</span>
              <span>Marketplace Notice &amp; Buyer Independent Due Diligence</span>
            </h2>
            <p className="leading-relaxed">
              Property information is provided directly by the seller. BhoomiMitra does not provide title verification, legal verification, survey certification, or government-authority certification of property listings. BhoomiMitra does not verify ownership, title, boundaries, measurements, encumbrances, approvals, land-use status, litigation status, or the authenticity of documents.
            </p>
            <p className="font-semibold text-slate-900">
              Examples of documents buyers should independently inspect. Requirements vary by property type, location, and applicable state law. Consult an independent property lawyer and appropriate government/revenue/survey authorities:
            </p>
            <ol className="list-decimal pl-5 space-y-2 text-slate-600 text-xs leading-relaxed">
              <li>
                <strong>Registered Sale Deed &amp; 30-Year Chain:</strong> Inspect the flow of registered title deeds and succession records covering a continuous 30-year period.
              </li>
              <li>
                <strong>Encumbrance Certificate (EC Form 15):</strong> Issued by the Sub-Registrar Office reflecting registered transactions and encumbrances on the property.
              </li>
              <li>
                <strong>Pahani / 7-12 Extract / ROR 1-B:</strong> Official Revenue Department record confirming agricultural possession, extent, soil type, and crop status (applicable per state).
              </li>
              <li>
                <strong>Survey Number &amp; FMB Map Sketch:</strong> Field Measurement Book (FMB) or revenue sketch validating physical boundaries, survey sub-division, and access roads.
              </li>
            </ol>
            <p className="text-xs text-slate-500 italic mt-2">
              Always engage an independent advocate and certified revenue surveyor before paying any advance or executing purchase agreements. BhoomiMitra assumes no liability for seller representations.
            </p>
          </section>

          {/* Section 6 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">6.</span>
              <span>Prohibited Activities, Abuse &amp; Reporting Mechanism</span>
            </h2>
            <p>Users agree not to engage in any of the following activities on BhoomiMitra:</p>
            <ul className="list-disc pl-5 space-y-1 text-slate-600">
              <li>Submitting fraudulent, duplicate, or non-existent property listings.</li>
              <li>Automated scraping, crawling, or harvesting of property data, images, or seller contact details.</li>
              <li>Circumventing platform authentication, manipulating OTP tokens, or exploiting API endpoints.</li>
              <li>Using buyer inquiry messaging for telemarketing, unsolicited commercial offers, or harassment.</li>
            </ul>
            <p className="text-xs text-slate-600 mt-2">
              Every listing includes a <strong>&quot;Report Listing&quot;</strong> mechanism. Users can flag unlawful, misleading, or infringing listings for immediate investigation and deactivation by platform moderation.
            </p>
          </section>

          {/* Section 7 */}
          <section className="space-y-3 pb-6 border-b border-slate-100">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">7.</span>
              <span>Limitation of Liability</span>
            </h2>
            <p>
              To the maximum extent permitted by applicable Indian law, BhoomiMitra, its founders, directors, employees, and technology partners shall not be liable for any direct, indirect, incidental, punitive, or consequential damages arising out of:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-slate-600">
              <li>Any transaction, agreement, financial deal, or dispute entered into between Buyers and Sellers.</li>
              <li>Any defect in title, boundary disputes, or fraudulent representations made by listing authors.</li>
              <li>Temporary platform downtime, payment gateway outages, or network interruptions.</li>
            </ul>
          </section>

          {/* Section 8 */}
          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-slate-900 flex items-center gap-2">
              <span className="text-[#c75e0a] font-mono">8.</span>
              <span>Governing Law &amp; Jurisdiction</span>
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the Republic of India. Any legal action, suit, or proceeding arising out of or related to these Terms or the Platform shall be subject to the exclusive jurisdiction of the competent courts located in <strong>Hyderabad, Telangana, India</strong>.
            </p>
          </section>
        </div>

        {/* Contact Support Section */}
        <div className="p-6 rounded-2xl bg-slate-900 text-white flex flex-col sm:flex-row items-center justify-between gap-4">
          <div>
            <h3 className="font-bold text-sm sm:text-base">Have legal questions or grievance queries?</h3>
            <p className="text-xs text-slate-400 mt-0.5">Reach out to our legal and compliance desk directly.</p>
          </div>
          <Link
            href="/contact"
            className="px-5 py-2.5 rounded-xl bg-[#FF9933] hover:bg-[#f07d12] text-white text-xs font-bold transition-colors shrink-0"
          >
            Contact Legal Desk
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
